
function mostrar1(){
document.getElementById("imagen1").style.visibility="visible";
document.getElementById("imagen2").style.visibility="hidden";
document.getElementById("imagen3").style.visibility="hidden";
document.getElementById("imagen4").style.visibility="hidden";
document.getElementById("imagen5").style.visibility="hidden";
document.getElementById("imagen6").style.visibility="hidden";
document.getElementById("imagen7").style.visibility="hidden";
document.getElementById("imagen8").style.visibility="hidden";
document.getElementById("imagen9").style.visibility="hidden";
document.getElementById("imagen10").style.visibility="hidden";
document.getElementById("imagen11").style.visibility="hidden";
}
function mostrar2(){
document.getElementById("imagen1").style.visibility="hidden";
document.getElementById("imagen2").style.visibility="visible";
document.getElementById("imagen3").style.visibility="hidden";
document.getElementById("imagen4").style.visibility="hidden";
document.getElementById("imagen5").style.visibility="hidden";
document.getElementById("imagen6").style.visibility="hidden";
document.getElementById("imagen7").style.visibility="hidden";
document.getElementById("imagen8").style.visibility="hidden";
document.getElementById("imagen9").style.visibility="hidden";
document.getElementById("imagen10").style.visibility="hidden";
document.getElementById("imagen11").style.visibility="hidden";
}
function mostrar3(){
document.getElementById("imagen1").style.visibility="hidden";
document.getElementById("imagen2").style.visibility="hidden";
document.getElementById("imagen3").style.visibility="visible";
document.getElementById("imagen4").style.visibility="hidden";
document.getElementById("imagen5").style.visibility="hidden";
document.getElementById("imagen6").style.visibility="hidden";
document.getElementById("imagen7").style.visibility="hidden";
document.getElementById("imagen8").style.visibility="hidden";
document.getElementById("imagen9").style.visibility="hidden";
document.getElementById("imagen10").style.visibility="hidden";
document.getElementById("imagen11").style.visibility="hidden";
}
function mostrar4(){
document.getElementById("imagen1").style.visibility="hidden";
document.getElementById("imagen2").style.visibility="hidden";
document.getElementById("imagen3").style.visibility="hidden";
document.getElementById("imagen4").style.visibility="visible";
document.getElementById("imagen5").style.visibility="hidden";
document.getElementById("imagen6").style.visibility="hidden";
document.getElementById("imagen7").style.visibility="hidden";
document.getElementById("imagen8").style.visibility="hidden";
document.getElementById("imagen9").style.visibility="hidden";
document.getElementById("imagen10").style.visibility="hidden";
document.getElementById("imagen11").style.visibility="hidden";
}
function mostrar5(){
document.getElementById("imagen1").style.visibility="hidden";
document.getElementById("imagen2").style.visibility="hidden";
document.getElementById("imagen3").style.visibility="hidden";
document.getElementById("imagen4").style.visibility="hidden";
document.getElementById("imagen5").style.visibility="visible";
document.getElementById("imagen6").style.visibility="hidden";
document.getElementById("imagen7").style.visibility="hidden";
document.getElementById("imagen8").style.visibility="hidden";
document.getElementById("imagen9").style.visibility="hidden";
document.getElementById("imagen10").style.visibility="hidden";
document.getElementById("imagen11").style.visibility="hidden";
}
function mostrar6(){
document.getElementById("imagen1").style.visibility="hidden";
document.getElementById("imagen2").style.visibility="hidden";
document.getElementById("imagen3").style.visibility="hidden";
document.getElementById("imagen4").style.visibility="hidden";
document.getElementById("imagen5").style.visibility="hidden";
document.getElementById("imagen6").style.visibility="visible";
document.getElementById("imagen7").style.visibility="hidden";
document.getElementById("imagen8").style.visibility="hidden";
document.getElementById("imagen9").style.visibility="hidden";
document.getElementById("imagen10").style.visibility="hidden";
document.getElementById("imagen11").style.visibility="hidden";

}
function mostrar7(){
document.getElementById("imagen1").style.visibility="hidden";
document.getElementById("imagen2").style.visibility="hidden";
document.getElementById("imagen3").style.visibility="hidden";
document.getElementById("imagen4").style.visibility="hidden";
document.getElementById("imagen5").style.visibility="hidden";
document.getElementById("imagen6").style.visibility="hidden";
document.getElementById("imagen7").style.visibility="visible";
document.getElementById("imagen8").style.visibility="hidden";
document.getElementById("imagen9").style.visibility="hidden";
document.getElementById("imagen10").style.visibility="hidden";
document.getElementById("imagen11").style.visibility="hidden";
}
function mostrar8(){
document.getElementById("imagen1").style.visibility="hidden";
document.getElementById("imagen2").style.visibility="hidden";
document.getElementById("imagen3").style.visibility="hidden";
document.getElementById("imagen4").style.visibility="hidden";
document.getElementById("imagen5").style.visibility="hidden";
document.getElementById("imagen6").style.visibility="hidden";
document.getElementById("imagen7").style.visibility="hidden";
document.getElementById("imagen8").style.visibility="visible";
document.getElementById("imagen9").style.visibility="hidden";
document.getElementById("imagen10").style.visibility="hidden";
document.getElementById("imagen11").style.visibility="hidden";
}
function mostrar9(){
document.getElementById("imagen1").style.visibility="hidden";
document.getElementById("imagen2").style.visibility="hidden";
document.getElementById("imagen3").style.visibility="hidden";
document.getElementById("imagen4").style.visibility="hidden";
document.getElementById("imagen5").style.visibility="hidden";
document.getElementById("imagen6").style.visibility="hidden";
document.getElementById("imagen7").style.visibility="hidden";
document.getElementById("imagen8").style.visibility="hidden";
document.getElementById("imagen9").style.visibility="visible";
document.getElementById("imagen10").style.visibility="hidden";
document.getElementById("imagen11").style.visibility="hidden";
}
function mostrar10(){
document.getElementById("imagen1").style.visibility="hidden";
document.getElementById("imagen2").style.visibility="hidden";
document.getElementById("imagen3").style.visibility="hidden";
document.getElementById("imagen4").style.visibility="hidden";
document.getElementById("imagen5").style.visibility="hidden";
document.getElementById("imagen6").style.visibility="hidden";
document.getElementById("imagen7").style.visibility="hidden";
document.getElementById("imagen8").style.visibility="hidden";
document.getElementById("imagen9").style.visibility="hidden";
document.getElementById("imagen10").style.visibility="visible";
document.getElementById("imagen11").style.visibility="hidden";
}
function mostrar11(){
document.getElementById("imagen1").style.visibility="hidden";
document.getElementById("imagen2").style.visibility="hidden";
document.getElementById("imagen3").style.visibility="hidden";
document.getElementById("imagen4").style.visibility="hidden";
document.getElementById("imagen5").style.visibility="hidden";
document.getElementById("imagen6").style.visibility="hidden";
document.getElementById("imagen7").style.visibility="hidden";
document.getElementById("imagen8").style.visibility="hidden";
document.getElementById("imagen9").style.visibility="hidden";
document.getElementById("imagen10").style.visibility="hidden";
document.getElementById("imagen11").style.visibility="visible";
}

function ocultar1(){
document.getElementById("imagen1").style.visibility="hidden";
document.getElementById("imagen2").style.visibility="hidden";
document.getElementById("imagen3").style.visibility="hidden";
document.getElementById("imagen4").style.visibility="hidden";
document.getElementById("imagen5").style.visibility="hidden";
document.getElementById("imagen6").style.visibility="hidden";
document.getElementById("imagen7").style.visibility="hidden";
document.getElementById("imagen8").style.visibility="hidden";
document.getElementById("imagen9").style.visibility="hidden";
document.getElementById("imagen10").style.visibility="hidden";
document.getElementById("imagen11").style.visibility="hidden";
}
